### ISSUE TITLE
iframe 'X-Frame-Options' to 'SAMEORIGIN' issue

### ISSUE THREAD

**Issue by laura-rodriguez** [filearts/plunker#114]
Yesterday and today I was not able to run code because of next issue:Refused to display 'https://run.plnkr.co/xxxxxxx/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by ggoodman** [comment]
Hi @laura-rodriguez can you give me some context on which browser you are using and whether you are using the main plunker editor, the embed, or the preview? Also, what browser are you using?

If you have a Plunk you can share to demonstrate the issue, please let me know.

**Comment by laura-rodriguez** [comment]
Hi @ggoodman, I am using chrome (Version 51.0.2704.103 m) but it also happens to me with FF.
This is the url I am using: https://plnkr.co/edit/UyInn4YpQlc5SeVUXuh6?p=preview
but it also happens with a new simple project: https://plnkr.co/edit/?p=preview

**Comment by ggoodman** [comment]
Hello @laura-rodriguez, other users have reported similar issues in the past and this has been due to corporate networks injecting that header. Neither the editor, nor the run server are issuing that header:

**Editor**
![image](https://cloud.githubusercontent.com/assets/50030/16469501/57ff07de-3e1f-11e6-8153-32d8a7f80437.png)

**Run server**
![image](https://cloud.githubusercontent.com/assets/50030/16469494/4c36af1a-3e1f-11e6-9d2d-02795801d17f.png)

Please consult whoever is responsible for the network environment that you run in to see if this change was recently introduced.

**Comment by laura-rodriguez** [comment]
@ggoodman  I have tried again, and it is working now. This issue not only happened to me, at my home, but also to my co-workers at the office and other friends at their home.

**Comment by ggoodman** [comment]
Hi @laura-rodriguez. I'm going to close the issue for now. If it re-appears, please open your developer console and show me exact what headers are being served both for the editor (https://plnkr.co/edit/) and for the preview (https://run.plnkr.co/<random_string>/).

**Comment by Sagarika85** [comment]
I am facing a similar issue.. 
![image](https://user-images.githubusercontent.com/38972442/39619604-163fb632-4fa6-11e8-8436-f94b78e390b9.png)
